# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

- pool:
  vmImage: windows-latest

- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean test  -Dkarate.options=classpath:API/FeatureFiles/RestfulBooker/ -Dtest=RestfulBookerRunner -Dkarate.env=prod'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
